extends: standard

parserOptions:
  sourceType: script

plugins:
  - chai-expect
  - chai-friendly

rules:
  arrow-parens:
  - warn
  - as-needed
  - requireForBlockBody: false
  no-shadow: warn
  no-unused-expressions: off
  no-var: warn
  object-curly-spacing: [ warn, always ]
  prefer-arrow-callback: warn
  prefer-const: warn
  strict: [ warn, global ]

  chai-friendly/no-unused-expressions: error
  chai-expect/missing-assertion: error
  chai-expect/terminating-properties: warn

  import/newline-after-import: warn
  import/no-absolute-path: warn
  import/no-dynamic-require: warn
  import/no-extraneous-dependencies: warn
  import/no-mutable-exports: warn
  import/order:
  - warn
  - groups:
    - [ builtin, external ]
    - [ sibling, index ]
    - parent
    newlines-between: always-and-inside-groups

  node/exports-style: [ warn, exports ]
  node/no-unsupported-features: warn
  node/shebang: warn

  promise/catch-or-return: warn
  promise/no-callback-in-promise: warn
  promise/no-native: warn
  promise/no-return-wrap: warn
